### ISSUE TITLE
Создание игрового поля

### ISSUE THREAD

**Issue by denyszamiatin** [denyszamiatin/backgammon#2]
Написать фрагмент кода для создания игрового поля (список из 24 списков)

**Comment by aleksandrmazurenko** [comment]
black_side1 = []
black_side2 = []
black_side3 = []
black_side4 = []
black_side5 = []
black_side6 = []
black_side7 = []
black_side8 = []
black_side9 = []
black_side10 = []
black_side11 = []
black_side12 = []

white_side13 = []
white_side14 = []
white_side15 = []
white_side16 = []
white_side17 = []
white_side18 = []
white_side19 = []
white_side20 = []
white_side21 = []
white_side22 = []
white_side23 = []
white_side24 = []
board = [black_side1, black_side2, black_side3, black_side4, black_side5, black_side6,
         black_side7, black_side8, black_side9, black_side10, black_side11, black_side12,
         white_side13, white_side14, white_side15, white_side16, white_side17, white_side18,
         white_side19, white_side20, white_side21, white_side22, white_side23, white_side24]

**Comment by denyszamiatin** [comment]
Для того, чтобы не писать одно и то же многократно, используются циклы

**Comment by aleksandrmazurenko** [comment]
Плохо понимаю циклы...

**Comment by alexzinoviev** [comment]
Closed. Pushed issue create board
