### ISSUE TITLE
Первоначальная расстановка шашек

### ISSUE THREAD

**Issue by denyszamiatin** [denyszamiatin/backgammon#3]
Написать фрагмент кода для расстановки 15 белых и черных шащек (добавление в список)

**Comment by aleksandrmazurenko** [comment]
black_checker1 = ('black_checker1')
black_checker2 = ('black_checker2')
black_checker3 = ('black_checker3')
black_checker4 = ('black_checker4')
black_checker5 = ('black_checker5')
black_checker6 = ('black_checker6')
black_checker7 = ('black_checker7')
black_checker8 = ('black_checker8')
black_checker9 = ('black_checker9')
black_checker10 = ('black_checker10')
black_checker11 = ('black_checker11')
black_checker12 = ('black_checker12')
black_checker13 = ('black_checker13')
black_checker14 = ('black_checker14')
black_checker15 = ('black_checker15')

white_checker1 = ('white_checker1')
white_checker2 = ('white_checker2')
white_checker3 = ('white_checker3')
white_checker4 = ('white_checker4')
white_checker5 = ('white_checker5')
white_checker6 = ('white_checker6')
white_checker7 = ('white_checker7')
white_checker8 = ('white_checker8')
white_checker9 = ('white_checker9')
white_checker10 = ('white_checker10')
white_checker11 = ('white_checker11')
white_checker12 = ('white_checker12')
white_checker13 = ('white_checker13')
white_checker14 = ('white_checker14')
white_checker15 = ('white_checker15')

black_side1 = []
black_side2 = []
black_side3 = []
black_side4 = []
black_side5 = []
black_side6 = []
black_side7 = []
black_side8 = []
black_side9 = []
black_side10 = []
black_side11 = []
black_side12 = [black_checker1, black_checker2, black_checker3, black_checker4, black_checker5, black_checker6, black_checker7,
                black_checker8, black_checker9, black_checker10, black_checker11, black_checker12, black_checker13, black_checker14,black_checker15]

white_side13 = []
white_side14 = []
white_side15 = []
white_side16 = []
white_side17 = []
white_side18 = []
white_side19 = []
white_side20 = []
white_side21 = []
white_side22 = []
white_side23 = []
white_side24 = [white_checker1, white_checker2, white_checker3, white_checker4, white_checker5, white_checker6, white_checker7,
                white_checker8, white_checker9, white_checker10, white_checker11, white_checker12, white_checker13, white_checker14, white_checker15]

board = [black_side1, black_side2, black_side3, black_side4, black_side5, black_side6,
         black_side7, black_side8, black_side9, black_side10, black_side11, black_side12,
         white_side13, white_side14, white_side15, white_side16, white_side17, white_side18,
         white_side19, white_side20, white_side21, white_side22, white_side23, white_side24]
