### ISSUE TITLE
Определение первого хода

### ISSUE THREAD

**Issue by denyszamiatin** [denyszamiatin/backgammon#4]
Написать фрагмент кода для определения первого хода путем бросания кубика

**Comment by aleksandrmazurenko** [comment]
import random
player1 = str(input('Enter a name: '))
player2 = str(input('Enter a name: '))
tessera1 = random.randint(1, 6)
tessera2 = random.randint(1, 6)
print(player1, 'threw the dice', tessera1)
print(player2, 'threw the dice', tessera2)
if tessera1 > tessera2:
    print('The first makes a move', player1)
else:
    print('The first makes a move', player2)

**Comment by edison12347** [comment]
Закомитился на этот ишью. Он выполнен, пока не могу залить код и закрыть ишью

**Comment by edison12347** [comment]
Successfully created first move function
