### ISSUE TITLE
запрос хода

### ISSUE THREAD

**Issue by SerialSata** [denyszamiatin/backgammon#9]
ИД: ход W / B
запрашиваем: 
1. номер поля, с которого будет ходить шашка (от 1 до 24)
2. на какое количество клеток ходим? 
проверяем ввод на валидность (введено первое число от 1 до 24, на этом поле есть шашки игрока (w, b), второе число от 1 до 6, )
Возвращаем в виде списка:
L = [номер поля, число ходов]

**Comment by RybachokDmytro** [comment]
"check_possible_turn function" has been added
